// Code generated by github.com/RobertoOrtis/fastgql, DO NOT EDIT.

package model

import (
	"github.com/RobertoOrtis/fastgql/example/scalars/external"
)

type Address struct {
	ID       external.ObjectID `json:"id"`
	Location *Point            `json:"location"`
}
